# Generated by Django 3.0.6 on 2020-05-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200521_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='название')),
                ('content', models.TextField(verbose_name='описание')),
                ('price', models.FloatField(default=0, verbose_name='цена')),
                ('contacts', models.TextField(verbose_name='контакты')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='изображение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='выводить в списке?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='автор объявления')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='main.SubRubric', verbose_name='рубрика')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='изображение')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='main.Bb', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'дополнительная иллюстрация',
                'verbose_name_plural': 'дополнительные иллюстрации',
            },
        ),
    ]
