# Generated by Django 3.0.6 on 2020-05-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_additionalimage_bb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
