# Generated by Django 3.0.6 on 2020-05-23 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200521_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, verbose_name='автор')),
                ('content', models.TextField(verbose_name='текст комментария')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выводить на экран?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='опубликован')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Bb', verbose_name='объявление')),
                ('parent_comment', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='main.Comment', verbose_name='комментарий к комментарию')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['created_at'],
            },
        ),
    ]
