# Generated by Django 3.0.6 on 2020-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200523_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='complain',
            field=models.BooleanField(default=False, verbose_name='пожаловаться?'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.SmallIntegerField(default=0, verbose_name='дислайки'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.SmallIntegerField(default=0, verbose_name='лайки'),
        ),
    ]
